"""add dialogue table

Revision ID: 03ad694cfa5a
Revises: 32b1e1420878
Create Date: 2024-09-22 01:41:06.142630

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '03ad694cfa5a'
down_revision = '32b1e1420878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('background_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('character_image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialogue')
    # ### end Alembic commands ###