"""change quest title

Revision ID: 32b1e1420878
Revises: 831841559232
Create Date: 2024-09-22 00:14:18.063845

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '32b1e1420878'
down_revision = '831841559232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('quest', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quest', 'city', ['city_id'], ['id'])
    op.drop_column('quest', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quest', type_='foreignkey')
    op.drop_column('quest', 'city_id')
    op.drop_column('quest', 'title')
    # ### end Alembic commands ###