"""Add city

Revision ID: 69d65c291d12
Revises: e5888b76b375
Create Date: 2024-09-21 23:27:20.176019

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '69d65c291d12'
down_revision = 'e5888b76b375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('city', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('city', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('city', sa.Column('picture_small_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('city', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('city', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('city', 'created_at')
    op.drop_column('city', 'picture_small_url')
    op.drop_column('city', 'longitude')
    op.drop_column('city', 'latitude')
    op.drop_column('city', 'title')
    # ### end Alembic commands ###